import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import TopAppBar from "./nav";
import Footer from "./footer";
import { ThemeProvider } from "./theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <TopAppBar />
          <div className="flex-1 min-h-screen py-12">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
